gcc -c first.c second.c
ar rcs libstaticlib.a first.o second.o
rm *.o #delete the o files generated by the compiler
#ar -x libstaticlib.a #now export the o files from the lib
gcc -c -c main.c #make the main file
gcc -o example main.o libstaticlib.a #link the main with the lib
rm *.a
rm *.o
./example #run the thing with the static lib
